#!/usr/bin/env bash
#
# This script will deploy a production build (handled by
# `react-scripts build`) to the DHIS specified in $DHIS2HOST. Since
# we're using ENV-variables in our application, we need to make sure a
# .env.production is found in this directory.
#
# Usage:
#
#      script/deploy <password-goes-here>

if [[ $# -eq 0 ]] ; then
    echo 'password required'
    exit 1
fi

export DHIS2HOST=$3
export DHIS2PASSWORD=$2
export DHIS2USER=$1
export APP=Hesabu


yarn build
rm $APP.zip || true
cd ./build && rm ./static/js/*.js.map && zip -r ../$APP.zip . && cd ..

printf "\nSubmitting app to ${DHIS2HOST} with ${DHIS2USER}\n"
curl -X POST -u "${DHIS2USER}:${DHIS2PASSWORD}" \
     -H "Accept: application/json" \
     --compressed \
     -F file=@$APP.zip \
     "${DHIS2HOST}/api/apps"

# I don't know exactly why we need to call the GET and the PUT
# requests here, but if we don't the DHIS sometimes doesn't seem to
# install the application.

printf "\nRefreshing apps:\n"
curl -sI -X GET -u "${DHIS2USER}:${DHIS2PASSWORD}" \
     -H "Accept: application/json" \
     "${DHIS2HOST}/api/apps" | head -n 1

curl -sI -X PUT -u "${DHIS2USER}:${DHIS2PASSWORD}" \
     -H "Accept: application/json" \
     "${DHIS2HOST}/api/apps" | head -n 1

printf "\nInstalled apps:\n"
curl -s -X GET -u "${DHIS2USER}:${DHIS2PASSWORD}" \
     -H "Accept: application/json" \
     "${DHIS2HOST}/api/apps" | jq -r '[.[] | [.name, .version]][] | join(" - ")'
