name: Build and publish to s3 bucket
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
            node-version: 12.x
      - run: yarn install
      - uses: paambaati/codeclimate-action@v2.2.4
            env:
                CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
            with:
                coverageCommand: yarn test:coverage


  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/develop'
    steps:
      - uses: actions/checkout@master

      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
            node-version: 12.x
      - run: sudo apt-get update && sudo apt-get install -y zip
      - run: yarn install
      - run: ./script/release
      - run: ./script/publish
        env:
          AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}